### ISSUE TITLE
[BE] email 송신 및 링크 클릭 내용 처리

### ISSUE THREAD

**Issue by OZestina** [42Seoul-Tea42/backend#5]
## 메일 송신이 필요한 경우
하기 두 개의 경우에 저장된 메일주소로 메일 송신이 필요합니다.

1. 이메일 인증용 메일 처리 (링크 유첨) -> 메인 인증 진행 후 사이트에서 진행 결과 확인
2. 비밀번호 리셋 메일 처리 (링크 유첨) -> 사이트 내 비밀번호 재설정 페이지 도달

두 메일 모두 특별한 랜덤 키가 있는 링크와 함께 전달되며 해당 링크를 클릭 시 필요한 내용이 실행되어야 하는데요,
현재의 구조가 백엔드는 프론트를 통해서만 접근이 가능하도록 되어있어서 생각대로 진행이 가능한 지 확인이 필요합니다.

(0) 유저가 링크를 클릭하면
(1) 링크에 해당하는 사이트 페이지로 이동하고
(2) 해당 사이트에서 바로 BE로 관련 API를 보내고
(3) BE에서 전달되는 응답을 (1)의 페이지에서 보여줘야 합니다.
상기 내용처럼 처리 가능한 지 확인해주세요!

만약 안된다면... 어떻게 우회할지 고민이 필요합니다.

**Comment by JaeJunday** [comment]
gmail + SMTP를 사용해서 구현한다고 했을때 이미 구현되있는 레퍼런스나 예제코드가 많아서 충분히 가능할 것 같아요.

**Comment by OZestina** [comment]
aa580b1998fa035d9f4e5307a22f5729b768c877
상기의 커밋으로 email 기능 구현 완료했습니다

**Comment by OZestina** [comment]
FE와의 논의를 통해 하기 방향으로 진행하기로 결정했습니다.

1. 이메일 상 링크: http://domain.com/user?page={int}&key={string}
2. 링크 클릭 시 FE페이지로 이동
- page 1: email 인증
- page 2: password 리셋
3. 페이지 상에서 API 요청
- page 1: 링크 클릭 시 자동으로 API 콜
- page 2: 페이지 상에서 pw입력 후 API 콜

**Comment by OZestina** [comment]
[BE] 추가적으로 하기 내용이 필요할 지 생각해보면 좋겠습니다.
- email 내 등록 해제 링크 추가
- email 전달 요청 관련 API 횟수 혹은 시간 제한
